### ISSUE TITLE
embedded_py option

### ISSUE THREAD

**Issue by youssefqarri** [MonetDBSolutions/monetdb-docker#10]
Hello,

I think it would be good to give the option to run the MonetDB with embedded_py

Cheers

**Comment by kutsurak** [comment]
Hi,

Currently there are two ways to do this for each database individually but not for the database farm itself:

For the first way you need to set a daemon password when you create the image. Something like:
`docker run -d -p 50000:50000 --name monetdb -e "MDB_DAEMON_PASS=daemonpass" -e "MDB_DB_ADMIN_PASS=adminpass" monetdb/monetdb`

This will create the default database `monetdb` as specified in the [readme](https://github.com/MonetDBSolutions/monetdb-docker/blob/master/README.rst).

Then from the host you can run
`monetdb -h localhost -P daemonpass set embedpy3=yes monetdb`
and this will enable the python integration for the database monetdb.

Alternatively, you can access the shell inside the container, after you start it, using 
`docker exec monetdb bash` and use `monetdb -h localhost set embedpy3=yes monetdb` there. This is relevant if you do not have the monetdb suite of tool installed in the host.

Now, by testing all this when writing this comment, I realized that numpy is missing from the image, so the databases cannot start with embedded python. This will be corrected, but in the meantime I suggest that you use the second way and install numpy with the command `dnf install python3-numpy` from the shell in the container before starting the database. This worked for me, but if you have any issues let me know.

**Comment by youssefqarri** [comment]
Hello,

Thank you for your reply. This is indeed the normal way to do it, however, in Docker, it should be in the entry point.

I managed to run the database farm by editing the last line of "scripts/entrypoint.sh" by running it using "mserver5" command, and adding "dnf install python3-numpy" in Dockerfile.

Maybe you could add an option in the run of the container to allow the user to activate embedpy3.

Thank you for your great work.

Regards

**Comment by kutsurak** [comment]
> Maybe you could add an option in the run of the container to allow the user to activate embedpy3.

Yes I agree. I am thinking that we should probably add another environment variable that sets database farm options and/or database options. 

Thank you for the feedback!

**Comment by kutsurak** [comment]
Small update on this: the rpm should now pull the numpy package when it gets installed: https://github.com/MonetDB/MonetDB/commit/8a27b36c39862a654e65db2988d40a9f7f56d941

This will take effect in the next bugfix release. In the meantime I will change the Dockerfile so that it explicitly installs `python3-numpy`.
