### ISSUE TITLE
Latest docker image from docker hub doesn't start

### ISSUE THREAD

**Issue by deepakpiscean** [MonetDBSolutions/monetdb-docker#9]
When we pull latest from monetdb/monetdb docker hub image, and then run it, it works. But subsequent docker start command fails for same container with below error 
sending SIGHUP to monetdbd[15] failed: No such process

Steps
1. docker pull monetdb/monetdb
2. docker run -d -P --name monetdb monetdb/monetdb
3. Now stop the container
4. Try docker start, or start from docker desktop, we get sending SIGHUP to monetdbd[15] failed: No such process.

Looks like problem with entrypoint.

**Comment by kutsurak** [comment]
Hi @deepakpiscean . I am sorry for this very late answer, somehow your issue fell through the cracks. I am going to look into this tomorrow.

**Comment by kutsurak** [comment]
Hi again @deepakpiscean. When you run or create the container for the first time you can specify a number of environment variables that configure the container. 

The bare minimum that you need to specify is `MDB_DB_ADMIN_PASS`, i.e. replace the second command above with:

```shell
docker run -d -P --name monetdb -e MDB_DB_ADMIN_PASS=<password> monetdb/monetdb
```
This will set the password for the `monetdb` user in the default database which is also named `monetdb`.

Take a look at the README of the project for a reference of all the possible variables that you can configure: https://github.com/MonetDBSolutions/monetdb-docker/blob/master/README.rst

With this change I was able to start and stop the container without problems. 

I will close this issue, but feel free to reopen it if something does not work for you or you need more information.
